name: build-server
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Version Tag'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build-ui
      run: |
        make server DOCKER_REPO=vorteil DOCKER_IMAGE=direktiv-ui DOCKER_TAG=${{ github.event.inputs.tags }}
