name: Build-UI-Components
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install
      - name: install bit
        run: |
          sudo npm install bit-bin --global
      - name: tag and export
        run: |
          bit tag --all
          bit export       